version: "3"
services:
  release:
    image: ${DOCKER_REGISTRY}milieuinfo/ubuntu-node:14.18.3
    environment:
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - no_proxy=${no_proxy}
      - HTTP_PROXY=${http_proxy}
      - HTTPS_PROXY=${https_proxy}
      - NO_PROXY=${no_proxy}
    extra_hosts:
      - "repository.milieuinfo.be:${REPOSITORY_FIXED_IP}"
    working_dir: /data
    volumes:
      - ${HOME:-.}/.npmrc:/root/.npmrc:ro
      - ${HOME:-.}/.gitconfig:/root/.gitconfig:ro
      - ${HOME:-.}/.git-credentials:/root/.git-credentials:ro
      - .:/data
    command: npx np "${release_version}"

