---
version: 2
plan:
  project-key: WEBCO
  key: VOASSETS
  name: vlaamse-overheid-assets

triggers:
  - polling: 130

variables:
  release_version: patch

stages:
  - Release:
      manual: true
      jobs:
        - Release

Release:
  key: REL
  tasks:
    - clean
    - script: |
        #!/usr/env/bin bash
        set -e
        echo "restore"
        /opt/scripts/git/git-repository-information-restore.sh
        echo "export git_repo"
        export git_repo="${bamboo_repository_git_repositoryUrl}"
        echo "export git_repo"
        export release_version="${bamboo.release_version}"
        echo "docker-compose"
        docker-compose -f docker-compose-release.yml run release
  final-tasks:
    - script: /opt/scripts/docker/stop-docker-containers.sh
  requirements:
    - REMOTE_ONLY

---
version: 2
plan:
  key: WEBCO-VOASSETS

plan-permissions:
  - groups:
      - bamboo-admin
      - bamboo-release
      - developer-admin
    permissions:
      - view
      - edit
      - build
      - clone
      - admin

